apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-pfe
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: postgres
  DB_PORT: '5432'
  DB_NAME: auth_service
  SERVER_PORT: '7070'
