apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app-pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: nexus-regcred
      containers:
        - name: auth-service
          image: 192.168.56.30/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: postgres-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7070
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7070
            initialDelaySeconds: 40
            periodSeconds: 20
