apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app-pfe
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 7070
      targetPort: 7070
  type: ClusterIP
