apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: app-pfe-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
