apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: nexus-regcred
      containers:
        - name: frontend
          image: 192.168.56.30/expense-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
