apiVersion: v1
kind: Namespace
metadata:
  name: app-pfe

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app-pfe
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: postgres-external
  namespace: app-pfe
  labels:
    kubernetes.io/service-name: postgres
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.56.40
ports:
  - name: postgres
    port: 5432
    protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-pfe
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_service
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: '7070'

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app-pfe
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: auth_user
  SPRING_DATASOURCE_PASSWORD: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app-pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: nexus-regcred
      containers:
        - name: auth-service
          image: 192.168.56.30/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SERVER_PORT
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7070
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7070
            initialDelaySeconds: 40
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app-pfe
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - name: http
      port: 7070
      targetPort: 7070
      nodePort: 30707
