---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-pfe
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deployment_service
  DB_HOST: postgres
  DB_PORT: '5432'
  SPRING_PROFILES_ACTIVE: prod
  AUTH_SERVER_PORT: '7070'
  GATEWAY_SERVER_PORT: '6060'
  CLOUD_PRICER_SERVER_PORT: '8090'
  DEPLOYMENT_SERVER_PORT: '8082'
  MAIL_HOST: smtp-relay.brevo.com
  MAIL_PORT: '587'
  MAIL_FROM: noreply@auth-service.local
  FRONTEND_BASE_URL: http://frontend
  MANAGEMENT_HEALTH_MAIL_ENABLED: 'false'
  ALERT_DISPATCH_ENABLED: 'false'
  AUTH_SERVICE_URL: http://auth-service:7070
  DEPLOYMENT_SERVICE_URL: http://deployment-service:8082
  CLOUD_PRICER_SERVICE_URL: http://cloud-pricer-service:8090
  VM_HOST_HOST: '192.168.56.1'
  VM_HOST_USER: 'mehdi'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: app-pfe
data:
  VITE_API_BASE_URL: /api/v1
