apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app-pfe
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: auth_user
  SPRING_DATASOURCE_PASSWORD: auth_password
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
